name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cpp-standard:
          - '98'
          - '11'
          - '20'
    steps:
      - uses: actions/checkout@v4
      - name: install GoogleTest
        run: .build/install-gtest
      - name: install include-what-you-use (iwyu)
        # NB: https://packages.ubuntu.com/jammy/iwyu apparently doesn't declare the `libclang-common-XXX-dev` package it
        # needs as a dependency (without it, `include-what-you-use` fails with "fatal error: 'stddef.h' file not found"
        # or similar), although this problem has been reported in 7 out of 7 bug reports at
        # https://bugs.launchpad.net/ubuntu/+source/iwyu, the oldest being from 2014.
        #
        # Therefore, we deliberately require a fixed version of `iwyu` along with the compatible
        # `libclang-common-XXX-dev` package. When a new version becomes available and we want to update to it, we'll
        # have to change this hardcoded version manually and bump the `libclang-common-XXX-dev` version accordingly (see
        # https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#clang-compatibility).
        run: |
          sudo apt-get update
          sudo apt-get install -y iwyu=8.17-1 libclang-common-13-dev
      - name: build
        env:
          CPP_STANDARD: ${{ matrix.cpp-standard }}
        run: |
          .build/build \
            -DCMAKE_CXX_STANDARD="$CPP_STANDARD" -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE='include-what-you-use;-Xiwyu;--verbose=3'
      - name: unittest
        run: .build/run-unittest
